// Generated by CoffeeScript 1.10.0
(function() {
  var A, B, _, cr, obj, ref, ref2, storage, tA, weak;

  _ = require('lodash')._;

  weak = require('weak');

  A = (function() {
    function A(a1, b1) {
      this.a = a1;
      this.b = b1;
    }

    A.prototype.__fa = function(c) {
      return a + b + c;
    };

    A.prototype.__fs = function(c) {
      return a + b - c;
    };

    return A;

  })();

  tA = function(c, clazz) {
    var j, k, len, ref1, results, v;
    console.log(clazz.prototype);
    ref1 = Object.keys(clazz.prototype);
    results = [];
    for (v = j = 0, len = ref1.length; j < len; v = ++j) {
      k = ref1[v];
      results.push(console.log(k, _.isFunction(clazz.prototype[k]), '==='));
    }
    return results;
  };

  tA(2, A);

  storage = {};

  B = (function() {
    function B(id1, i1, st) {
      var i, j, ref1;
      this.id = id1;
      this.i = i1;
      this.st = st;
      this.arr = [];
      for (i = j = 0, ref1 = this.i; 0 <= ref1 ? j <= ref1 : j >= ref1; i = 0 <= ref1 ? ++j : --j) {
        this.arr.push(i + " item");
      }
    }

    B.prototype.del = function() {
      this.st[this.id] = null;
      return gc();
    };

    return B;

  })();

  cr = function(id, i) {
    storage[id] = new B(id, i, storage);
    return weak(storage[id]);
  };

  ref = cr(1, 2);

  obj = {
    a: true,
    foo: 'bar'
  };

  ref = weak(obj, function() {
    return console.log('===herher');
  });

  console.log('=?', ref === obj);

  console.log('=?', ref.a === obj.a);

  ref2 = ref;

  console.log(obj, typeof ref.a, weak.isDead(ref));

  console.log(obj, typeof ref2.a, weak.isDead(ref2));

  obj = null;

  gc();

  console.log(obj, typeof ref.a, weak.isDead(ref));

  console.log(obj, typeof ref2.a, weak.isDead(ref2));

}).call(this);
